# Generated by Django 4.2.4 on 2023-08-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements81', '0002_advertisements81_bu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements81',
            table='advertisements',
        ),
    ]
